# Extract Data from SnapDeal
### Product : Name, Actual price, Discount price, Rating, Image url, Product url
### Link for mobile catregory 
: https://www.snapdeal.com/products/mobiles-mobile-phones?sort=plrty#bcrumbLabelId:175

In [406]:
# importing libraries
import csv
from bs4 import BeautifulSoup

# Firefox & Chorme
from selenium import webdriver

import time

import pandas as pd

## Startup the webdriver

In [360]:
driver = webdriver.Chrome('C:/webdriver/chromedriver.exe')

In [361]:
url = 'https://www.snapdeal.com/products/mobiles-mobile-phones?sort=plrty#bcrumbLabelId:175'
driver.get(url)

## Extract the collection

In [362]:
soup = BeautifulSoup(driver.page_source,'html.parser')

In [363]:
results = soup.find_all('div',{'class':'product-tuple-listing'})

## Prototype the record

In [364]:
item = results[0]

In [365]:
# URL of a product
atag = item.find('a',{'class':'dp-widget-link noUdLine hashAdded'})
url = atag.get('href')
url

'https://www.snapdeal.com/product/redmi-9-64gb-4-gb/646372370923#bcrumbLabelId:175'

In [368]:
# Image URL
imgtag = item.find('img',{'class':'product-image'})
url = imgtag.get('src')
url

'https://n1.sdlcdn.com/imgs/j/r/t/230X258_sharpened/Redmi-9-64GB-4-GB-SDL649851775-1-1537a.jpg'

In [369]:
# Name of a product
name = item.find('p',{'class':'product-title'}).text
name

'Redmi 9 ( 64GB , 4 GB ) Black'

In [370]:
# Actual price
actPrice = item.find('span',{'class':'lfloat product-desc-price strike'}).text
actPrice

'Rs. 10,999'

In [1]:
# Discount price
disPrice = item.find('span',{'class':'lfloat product-price'}).text
disPrice

NameError: name 'item' is not defined

## Generalize pattern

In [396]:
def extract_record(item):
    """Extract and return data from a single record"""
    
    # URL of a product
    atag = item.find('a',{'class':'dp-widget-link hashAdded'})
    url = atag.get('href')
    
    # Image URL
    imgtag = item.find('img',{'class':'product-image'})
    imgUrl = imgtag.get('src')

    try :
        # Name of a product
        name = item.find('p',{'class':'product-title'}).text
    except AttributeError:
        return
    
    try:
        # Actual & Discount price
        actPrice = item.find('span',{'class':'lfloat product-desc-price strike'}).text
        disPrice = item.find('span',{'class':'lfloat product-price'}).text
    except AttributeError:
        actPrice = ''
        disPrice = ''
        
    result = (name,actPrice,disPrice,imgUrl,url)
    
    return result

In [397]:
records = []
results = soup.find_all('div',{'class':'product-tuple-listing'})

for item in results:
    record = extract_record(item)
    if record:
        records.append(record)

In [398]:
records

[('Redmi 9 ( 64GB , 4 GB ) Black',
  'Rs. 10,999',
  'Rs.  9,499',
  'https://n1.sdlcdn.com/imgs/j/r/t/230X258_sharpened/Redmi-9-64GB-4-GB-SDL649851775-1-1537a.jpg',
  'https://www.snapdeal.com/product/redmi-9-64gb-4-gb/646372370923#bcrumbLabelId:175'),
 ('Xolo Era 2 ( 8GB , 1 GB ) Black',
  'Rs. 5,299',
  'Rs.  4,463',
  'https://n2.sdlcdn.com/imgs/h/h/d/230X258_sharpened/1-31100.jpg',
  'https://www.snapdeal.com/product/xolo-era-2-8gb-black/5188147410095998352#bcrumbLabelId:175'),
 ('Gionee s11 ( 32GB , 4 GB ) Black',
  'Rs. 15,399',
  'Rs.  7,000',
  'https://n2.sdlcdn.com/imgs/j/s/0/230X258_sharpened/Gionee-s11-32GB-4-GB-SDL288728047-1-84064.png',
  'https://www.snapdeal.com/product/gionee-s11-32gb-4-gb/636807898611#bcrumbLabelId:175'),
 ('Redmi 9 Power ( 64GB , 4 GB ) Black',
  'Rs. 13,999',
  'Rs.  11,399',
  'https://n1.sdlcdn.com/imgs/j/r/6/230X258_sharpened/Redmi-9-Power-64GB-4-SDL961566844-1-b0a59.jpeg',
  'https://www.snapdeal.com/product/redmi-9-power-64gb-4/6917529675684212900#bcrumbLabelId:175'),
 ('Realme Narzo 10A ( 32GB , 3 GB ) Blue',
  'Rs. 10,999',
  'Rs.  9,803',
  'https://n2.sdlcdn.com/imgs/j/f/c/230X258_sharpened/Realme-Narzo-10A-32GB-3-SDL217157000-1-5eba1.jpeg',
  'https://www.snapdeal.com/product/realme-narzo-10a-32gb-3/682371075796#bcrumbLabelId:175'),
 ('Xolo Era 2 ( 8GB , 1 GB ) Pyramid Gold',
  'Rs. 5,299',
  'Rs.  4,463',
  'https://n1.sdlcdn.com/imgs/h/h/d/230X258_sharpened/1-1bfa8.jpg',
  'https://www.snapdeal.com/product/xolo-era-2-8gb-black/6341068914702845328#bcrumbLabelId:175'),
 ('Redmi 9A ( 32GB , 2 GB ) Green',
  'Rs. 8,499',
  'Rs.  7,899',
  'https://n3.sdlcdn.com/imgs/j/o/i/230X258_sharpened/Redmi-9A-32GB-2-GB-SDL880361485-1-8764b.jpeg',
  'https://www.snapdeal.com/product/redmi-9a-32gb-2-gb/8070451206464593453#bcrumbLabelId:175'),
 ('Realme Narzo 20 ( 64GB , 4 GB ) Victory Blue',
  'Rs. 12,999',
  'Rs.  11,999',
  'https://n2.sdlcdn.com/imgs/j/r/o/230X258_sharpened/Realme-Narzo-20-64GB-4-SDL337945507-1-f5568.jpeg',
  'https://www.snapdeal.com/product/realme-narzo-20-64gb-4/665892836468#bcrumbLabelId:175'),
 ('Redmi 9 ( 64GB , 4 GB ) Black',
  'Rs. 10,999',
  'Rs.  9,503',
  None,
  'https://www.snapdeal.com/product/redmi-9-64gb-4-gb/5188147435875381757#bcrumbLabelId:175'),
 ('Realme XT ( 64GB , 6 GB ) White',
  'Rs. 18,999',
  'Rs.  17,999',
  None,
  'https://www.snapdeal.com/product/realme-xt-64gb-6-gb/661600837444#bcrumbLabelId:175'),
 ('Redmi 6A ( 16GB , 2 GB ) Black',
  'Rs. 7,399',
  'Rs.  7,004',
  None,
  'https://www.snapdeal.com/product/redmi-6a-16gb-2-gb/674659825952#bcrumbLabelId:175'),
 (' Samsung M20 ( 64GB , 4 GB ) Blue',
  'Rs. 11,999',
  'Rs.  10,999',
  None,
  'https://www.snapdeal.com/product/samsung-mobile-samsung-m20-64gb/5764608163883522350#bcrumbLabelId:175'),
 ('Samsung Galaxy M31 ( 128GB , 6 GB ) Black',
  'Rs. 19,999',
  'Rs.  18,003',
  None,
  'https://www.snapdeal.com/product/samsung-galaxy-m31-128gb-6/670462998808#bcrumbLabelId:175'),
 ('Realme Narzo 30A ( 32GB , 3 GB ) Blue',
  'Rs. 9,999',
  'Rs.  9,499',
  None,
  'https://www.snapdeal.com/product/realme-narzo-30a-32gb-3/639295906541#bcrumbLabelId:175'),
 ('Redmi 9 Power ( 64GB , 4 GB ) Power Blue',
  'Rs. 13,999',
  'Rs.  11,499',
  None,
  'https://www.snapdeal.com/product/redmi-9-power-64gb-4/7493990427987636388#bcrumbLabelId:175'),
 ('Gionee s11 lite ( 32 GB , 4 GB ) Blue',
  'Rs. 8,999',
  'Rs.  7,004',
  None,
  'https://www.snapdeal.com/product/gionee-blue-s11-lite-32/5764608157785105335#bcrumbLabelId:175'),
 ('Oppo A15s ( 64GB , 4 GB ) Silver',
  'Rs. 13,990',
  'Rs.  12,990',
  None,
  'https://www.snapdeal.com/product/oppo-a15s-64gb-4-gb/5764608177391873536#bcrumbLabelId:175'),
 ('Redmi 9A ( 32GB , 2 GB ) Black',
  'Rs. 8,999',
  'Rs.  7,749',
  None,
  'https://www.snapdeal.com/product/redmi-9a-32gb-2-gb/6917529701857746477#bcrumbLabelId:175'),
 ('MI 11x 5G ( 128GB , 6 GB ) Black',
  'Rs. 33,999',
  'Rs.  30,499',
  None,
  'https://www.snapdeal.com/product/mi-11x-5g-128gb-6/645527672600#bcrumbLabelId:175'),
 ('Samsung M02s ( 32GB , 3 GB ) Blue',
  'Rs. 10,499',
  'Rs.  9,999',
  None,
  'https://www.snapdeal.com/product/samsung-m02s-32gb-3-gb/6917529706520383582#bcrumbLabelId:175')]

## Extract Star rating
using product link

In [382]:
#Product URL
rate_url = []

for i in range(0,20):
    rate_url.append(records[i][0])
    
print(rate_url)

['https://www.snapdeal.com/product/redmi-9-64gb-4-gb/646372370923#bcrumbLabelId:175', 'https://www.snapdeal.com/product/xolo-era-2-8gb-black/5188147410095998352#bcrumbLabelId:175', 'https://www.snapdeal.com/product/gionee-s11-32gb-4-gb/636807898611#bcrumbLabelId:175', 'https://www.snapdeal.com/product/redmi-9-power-64gb-4/6917529675684212900#bcrumbLabelId:175', 'https://www.snapdeal.com/product/realme-narzo-10a-32gb-3/682371075796#bcrumbLabelId:175', 'https://www.snapdeal.com/product/xolo-era-2-8gb-black/6341068914702845328#bcrumbLabelId:175', 'https://www.snapdeal.com/product/redmi-9a-32gb-2-gb/8070451206464593453#bcrumbLabelId:175', 'https://www.snapdeal.com/product/realme-narzo-20-64gb-4/665892836468#bcrumbLabelId:175', 'https://www.snapdeal.com/product/redmi-9-64gb-4-gb/5188147435875381757#bcrumbLabelId:175', 'https://www.snapdeal.com/product/realme-xt-64gb-6-gb/661600837444#bcrumbLabelId:175', 'https://www.snapdeal.com/product/redmi-6a-16gb-2-gb/674659825952#bcrumbLabelId:175', 'https://www.snapdeal.com/product/samsung-mobile-samsung-m20-64gb/5764608163883522350#bcrumbLabelId:175', 'https://www.snapdeal.com/product/samsung-galaxy-m31-128gb-6/670462998808#bcrumbLabelId:175', 'https://www.snapdeal.com/product/realme-narzo-30a-32gb-3/639295906541#bcrumbLabelId:175', 'https://www.snapdeal.com/product/redmi-9-power-64gb-4/7493990427987636388#bcrumbLabelId:175', 'https://www.snapdeal.com/product/gionee-blue-s11-lite-32/5764608157785105335#bcrumbLabelId:175', 'https://www.snapdeal.com/product/oppo-a15s-64gb-4-gb/5764608177391873536#bcrumbLabelId:175', 'https://www.snapdeal.com/product/redmi-9a-32gb-2-gb/6917529701857746477#bcrumbLabelId:175', 'https://www.snapdeal.com/product/mi-11x-5g-128gb-6/645527672600#bcrumbLabelId:175', 'https://www.snapdeal.com/product/samsung-m02s-32gb-3-gb/6917529706520383582#bcrumbLabelId:175']

In [384]:
def get_star_rating(url):
    """Extract and return product name & rating"""

    driver.get(f'{url}')
    rating_result = BeautifulSoup(driver.page_source, 'html.parser')

    try:
        # Product Name
        product_name = rating_result.find('h1', {'itemprop': 'name'}).text.strip()
    except AttributeError:
        return

    try:
        # Product Rating
        rating_count = rating_result.find('span', {'class': 'avrg-rating'}).text.strip()
    except AttributeError:
        rating_count = '0'

    values = (product_name, rating_count)

    return values

In [385]:
# Store Name & Rating
df = []

# Iterating the URL List
for item in rate_url:
    record = get_star_rating(item)
    
    if record:
        df.append(record)
        
        # sleep for 1sec
        time.sleep(1)

In [402]:
df = list(set(df))
df[0]

('Xolo Era 2 ( 8GB , 1 GB ) Black', '(3.8)')

In [478]:
Product_names = []
Product_rating = []

for i in range(0,20):
    prod_name2 = df[i][0]
    pro_rat = df[i][1]
    
    Product_names.append(prod_name2)
    Product_rating.append(pro_rat)
    
Product_names = pd.DataFrame(Product_names, columns = ['Product_name'])
Product_rating = pd.DataFrame(Product_rating, columns = ['Rating'])
new_data = pd.concat([Product_names,Product_rating],axis=1)

In [479]:
new_data

                                    Product_name Rating
0                Xolo Era 2 ( 8GB , 1 GB ) Black  (3.8)
1         Xolo Era 2 ( 8GB , 1 GB ) Pyramid Gold  (3.8)
2                    Lenovo ( 8GB , 2 GB ) Black  (4.0)
3              Samsung M02s ( 32GB , 3 GB ) Blue      0
4                 Redmi 9A ( 32GB , 2 GB ) Black  (4.3)
5          Realme Narzo 30A ( 32GB , 3 GB ) Blue      0
6          Realme Narzo 10A ( 32GB , 3 GB ) Blue      0
7       Redmi 9 Power ( 64GB , 4 GB ) Power Blue  (4.3)
8                  Redmi 9 ( 64GB , 4 GB ) Black  (3.5)
9            Redmi 9 Power ( 64GB , 4 GB ) Black  (4.3)
10  Realme Narzo 20 ( 64GB , 4 GB ) Victory Blue  (4.0)
11                Redmi 9A ( 32GB , 2 GB ) Green  (4.3)
12              MI 11x 5G ( 128GB , 6 GB ) Black      0
13       Samsung Galaxy M11 ( 64GB , 4 GB ) Blue  (5.0)
14     Samsung Galaxy M31 ( 128GB , 6 GB ) Black      0
15              Gionee s11 ( 32GB , 4 GB ) Black      0
16                Redmi 6A ( 16GB , 2 GB ) Black      0
17                 Redmi 9 ( 64GB , 4 GB ) Black  (4.3)
18              Oppo A15s ( 64GB , 4 GB ) Silver      0
19         Gionee s11 lite ( 32 GB , 4 GB ) Blue  (3.4)

In [562]:
product_name = []
actual_price = []
discount_price = []
image_url = []
product_url = []

for i in range(0,20):
    prod_name = records[i][0]
    act_price = records[i][1]
    dis_price = records[i][2]
    img_url = records[i][3]
    prod_url = records[i][4]
    
    product_name.append(prod_name)
    actual_price.append(act_price)
    discount_price.append(dis_price)
    image_url.append(img_url)
    product_url.append(prod_url)

product_name = pd.DataFrame(product_name, columns = ['Product_name'])
actual_price = pd.DataFrame(actual_price, columns = ['Actual_price'])
discount_price = pd.DataFrame(discount_price, columns = ['Discount_price'])
image_url = pd.DataFrame(image_url, columns = ['Image_url'])
product_url = pd.DataFrame(product_url, columns = ['Product_url'])

In [564]:
product_dataset = pd.concat([product_name,actual_price,discount_price,image_url,product_url],axis=1)

# SnapDeal Mobile Phone Dataset

In [565]:
product_dataset

,Product_name,Actual_price,Discount_price,Image_url,Product_url
0,"Redmi 9 ( 64GB , 4 GB ) Black","Rs. 10,999","Rs. 9,499",https://n1.sdlcdn.com/imgs/j/r/t/230X258_sharp...,https://www.snapdeal.com/product/redmi-9-64gb-...
1,"Xolo Era 2 ( 8GB , 1 GB ) Black","Rs. 5,299","Rs. 4,463",https://n2.sdlcdn.com/imgs/h/h/d/230X258_sharp...,https://www.snapdeal.com/product/xolo-era-2-8g...
2,"Gionee s11 ( 32GB , 4 GB ) Black","Rs. 15,399","Rs. 7,000",https://n2.sdlcdn.com/imgs/j/s/0/230X258_sharp...,https://www.snapdeal.com/product/gionee-s11-32...
3,"Redmi 9 Power ( 64GB , 4 GB ) Black","Rs. 13,999","Rs. 11,399",https://n1.sdlcdn.com/imgs/j/r/6/230X258_sharp...,https://www.snapdeal.com/product/redmi-9-power...
4,"Realme Narzo 10A ( 32GB , 3 GB ) Blue","Rs. 10,999","Rs. 9,803",https://n2.sdlcdn.com/imgs/j/f/c/230X258_sharp...,https://www.snapdeal.com/product/realme-narzo-...
5,"Xolo Era 2 ( 8GB , 1 GB ) Pyramid Gold","Rs. 5,299","Rs. 4,463",https://n1.sdlcdn.com/imgs/h/h/d/230X258_sharp...,https://www.snapdeal.com/product/xolo-era-2-8g...
6,"Redmi 9A ( 32GB , 2 GB ) Green","Rs. 8,499","Rs. 7,899",https://n3.sdlcdn.com/imgs/j/o/i/230X258_sharp...,https://www.snapdeal.com/product/redmi-9a-32gb...
7,"Realme Narzo 20 ( 64GB , 4 GB ) Victory Blue","Rs. 12,999","Rs. 11,999",https://n2.sdlcdn.com/imgs/j/r/o/230X258_sharp...,https://www.snapdeal.com/product/realme-narzo-...
8,"Redmi 9 ( 64GB , 4 GB ) Black","Rs. 10,999","Rs. 9,503",None,https://www.snapdeal.com/product/redmi-9-64gb-...
9,"Realme XT ( 64GB , 6 GB ) White","Rs. 18,999","Rs. 17,999",None,https://www.snapdeal.com/product/realme-xt-64g...
10,"Redmi 6A ( 16GB , 2 GB ) Black","Rs. 7,399","Rs. 7,004",None,https://www.snapdeal.com/product/redmi-6a-16gb...
11,"Samsung M20 ( 64GB , 4 GB ) Blue","Rs. 11,999","Rs. 10,999",None,https://www.snapdeal.com/product/samsung-mobil...
12,"Samsung Galaxy M31 ( 128GB , 6 GB ) Black","Rs. 19,999","Rs. 18,003",None,https://www.snapdeal.com/product/samsung-galax...
13,"Realme Narzo 30A ( 32GB , 3 GB ) Blue","Rs. 9,999","Rs. 9,499",None,https://www.snapdeal.com/product/realme-narzo-...
14,"Redmi 9 Power ( 64GB , 4 GB ) Power Blue","Rs. 13,999","Rs. 11,499",None,https://www.snapdeal.com/product/redmi-9-power...
15,"Gionee s11 lite ( 32 GB , 4 GB ) Blue","Rs. 8,999","Rs. 7,004",None,https://www.snapdeal.com/product/gionee-blue-s...
16,"Oppo A15s ( 64GB , 4 GB ) Silver","Rs. 13,990","Rs. 12,990",None,https://www.snapdeal.com/product/oppo-a15s-64g...
17,"Redmi 9A ( 32GB , 2 GB ) Black","Rs. 8,999","Rs. 7,749",None,https://www.snapdeal.com/product/redmi-9a-32gb...
18,"MI 11x 5G ( 128GB , 6 GB ) Black","Rs. 33,999","Rs. 30,499",None,https://www.snapdeal.com/product/mi-11x-5g-128...
19,"Samsung M02s ( 32GB , 3 GB ) Blue","Rs. 10,499","Rs. 9,999",None,https://www.snapdeal.com/product/samsung-m02s-...

In [566]:
new_data

                                    Product_name Rating
0                Xolo Era 2 ( 8GB , 1 GB ) Black  (3.8)
1         Xolo Era 2 ( 8GB , 1 GB ) Pyramid Gold  (3.8)
2                    Lenovo ( 8GB , 2 GB ) Black  (4.0)
3              Samsung M02s ( 32GB , 3 GB ) Blue      0
4                 Redmi 9A ( 32GB , 2 GB ) Black  (4.3)
5          Realme Narzo 30A ( 32GB , 3 GB ) Blue      0
6          Realme Narzo 10A ( 32GB , 3 GB ) Blue      0
7       Redmi 9 Power ( 64GB , 4 GB ) Power Blue  (4.3)
8                  Redmi 9 ( 64GB , 4 GB ) Black  (3.5)
9            Redmi 9 Power ( 64GB , 4 GB ) Black  (4.3)
10  Realme Narzo 20 ( 64GB , 4 GB ) Victory Blue  (4.0)
11                Redmi 9A ( 32GB , 2 GB ) Green  (4.3)
12              MI 11x 5G ( 128GB , 6 GB ) Black      0
13       Samsung Galaxy M11 ( 64GB , 4 GB ) Blue  (5.0)
14     Samsung Galaxy M31 ( 128GB , 6 GB ) Black      0
15              Gionee s11 ( 32GB , 4 GB ) Black      0
16                Redmi 6A ( 16GB , 2 GB ) Black      0
17                 Redmi 9 ( 64GB , 4 GB ) Black  (4.3)
18              Oppo A15s ( 64GB , 4 GB ) Silver      0
19         Gionee s11 lite ( 32 GB , 4 GB ) Blue  (3.4)